url: https://vikasdhiman.info
baseurl: /ECE490-Neural-Networks
remote_theme:  samarsault/plainwhite-jekyll
title: Neural Networks (ECE490) at the University of Maine
author: Vikas Dhiman
description: Neural Networks (ECE490) at the University of Maine
show_excerpts: true

# Build settings
markdown: kramdown
permalink: /posts/:path/
paginate: 10


header_pages:
  - schedule.md
  - syllabus.md
  - categories/lectures.md
  - categories/announcements.md

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Neural Networks (ECE490)
  tagline: |
     Autograd, Optimization, Visualization

  sitemap: true

  search: true

  html_lang: "en"

  navigation:
    - title: Syllabus
      url: "https://docs.google.com/document/d/e/2PACX-1vS73JkG6EWlYAphXwjDxdVcryT7SmCGtot2wpqLQfjV5KrozNmVwHoVtT2qyAvDERZk0y2dBfVU_QJE/pub"
    - title: Schedule
      url: "/schedule"
    - title: Zoom link
      url: "https://maine.zoom.us/j/87817514688?pwd=WkRsNnlZaitkYXpwQk5RZ2tJd3ZHUT09"
    - title: Similar courses
      url: "/similar-courses"
    - title: Office hour appointment
      url: "https://calendar.app.google/xB6KFEtRnVmqcuaL7"

  portfolio_image: assets/Neural_network_example.svg
    
  condensed_mobile:
    - Home
    - Schedule
    - Similar courses
